version: "3.7"
services:
  cypress:
    image: cypress/included:9.7.0
    environment:
      - CYPRESS_browser=firefox
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.config.js:/e2e/cypress.config.js
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run"]
