name: Run Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker image for Cypress
        uses: docker://cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

  playwright-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker image for Playwright
        uses: docker://mcr.microsoft.com/playwright:v1.39.0-jammy

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test
